#!/usr/bin/env bash

set -eu

root=$(git rev-parse --show-toplevel)

function create_schema() {
    mysql -h 127.0.0.1 -uroot < ${root}/pkg/storage/metadb/mysql.sql
}

function run_syncyd() {
    docker run -it --rm docker.io/library/syncyd
}

function main() {
    create_schema
    ${root}/script/build
    run_syncyd
}

main